# Generated by Django 5.0.6 on 2024-05-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
