# Generated by Django 5.0.6 on 2024-05-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_img_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='info/', verbose_name='Img info')),
                ('name', models.CharField(max_length=50, verbose_name='Name info')),
                ('text', models.TextField(verbose_name='Text info')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='main.product')),
            ],
        ),
    ]
