# Generated by Django 5.0.6 on 2024-05-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cat name')),
                ('img', models.ImageField(upload_to='Category/', verbose_name='Cat img')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prod name')),
                ('img', models.ImageField(upload_to='Product/', verbose_name='Prod img')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('count', models.CharField(max_length=10, verbose_name='Count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.category')),
            ],
        ),
    ]
