# Generated by Django 5.0.6 on 2024-05-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cat_alter_category_name_category_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
