# Generated by Django 5.0.6 on 2024-05-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_info_remove_category_cat_delete_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='main.product'),
        ),
    ]
